version: '3.8'
services:
  app:
    build: .
    ports:
      - "5173:5173"
    environment:
      - VITE_PROMO=Hati
      - VITE_ENV=dev
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
